name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Make script executable
      run: chmod +x .github/actions/hello-devops/hello.sh
      
    - name: Hello World Action
      uses: ./.github/actions/hello-devops